development:
  adapter: mysql2
  encoding: utf8
  database: batterup
  username: batterupuser
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: batterup_test
  username: batterupuser
  password:
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
